yaml.load("""
base:
  image: "ubuntu-base"
  release: "18.04"
  sub: ".4"
  file: $image.lower$-$release$$sub$-base-$ARCH$.tar.gz
  url: http://cdimage.ubuntu.com/$image$/releases/$release$/release

download:
  url: $base.url$/$base.file$
""", Loader=yaml.FullLoader)
