= YAMLPy Guide
João Pinto <lamego.pinto@gmail.com>
:toc: left
:source-highlighter: prettify
:stylesheet: css/adoc-colony.css

== Introduction
An YAMLPy document is a valid YAML document extended with dynamic elements, in order to transform the document into a final YAML, YAMLPy documents must be rendered using the  `yamlpy` utility.

CAUTION: YAMLPy document rendering is equivalent to a python script execution. You should not bindly render documents obtained from untrusted sources.

== Python Dynamic Elements
Strings found between consecutive `($)` «dollar signs» are considered dynamic elements, their content is evaluated in a python runtime, the result of the evalution replaces the dynamic string.

=== Constant Expressions
Constant expressions can be used to preserve calculation formulas in the source and only the result in the output.

[cols="1a,1a", options="header"]
.Constant expression examples
|===
|YAMLPy|YAML|
[source, yaml]
include::../yamlpy/tests/files/expressions.yaml[]
|
[source, yaml]
include::../yamlpy/tests/files/expressions_result.yaml[]
|===

=== Sibling References

Sibling references can be used to facilitate string composition and transformation, all sibling keys in a map are available to the python execution as variables matching their key names.

[cols="1a,1a", options="header"]
.Sibling reference examples
|===
|YAMLPy
|Rendered YAML

|
[source, yaml]
release: "18.04"
update: ".4"
url: http://releases.ubuntu.com/$release$/ubuntu-$release$update$-desktop-amd64.iso
|
[source, yaml]
release: "18.04"
update: ".4"
url: http://releases.ubuntu.com/18.04/ubuntu-18.04.4-desktop-amd64.iso

|
[source, yaml]
original_color: BlUe.
normal_color: $original_color.lower().strip(".")$
|
[source, yaml]
original_color: BlUe.
normal_color: blue
|===

include::internal_nodes.adoc[]
